apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-client1-to-nginx
  namespace: apps
spec:
  selector: "app == 'nginx'" # targets pods with label app=nginx
  types:
    - Ingress
  ingress:
    - action: Allow
      protocol: TCP
      source:
        selector: "run == 'client1'" # only allow traffic from pods with label run=client1
        namespaceSelector: "env == 'dev'"
      destination:
        ports:
          - 80
